"use strict";
var myDynamicVar;
myDynamicVar = 100;
myDynamicVar = null;
myDynamicVar = {};
myDynamicVar = '';
myDynamicVar = 'Hola';
var rta = myDynamicVar.toLowerCase();
console.log(rta);
myDynamicVar = 1212;
var rta2 = myDynamicVar.toString;
console.log(rta2);
