"use strict";
exports.__esModule = true;
var operaciones_js_1 = require("./operaciones.js");
var suma = (0, operaciones_js_1.sum)(10, 20);
console.log("Suma: " + suma);
var resta = (0, operaciones_js_1.res)(20, 30);
console.log("Resta: " + resta);
var multiplicar = (0, operaciones_js_1.mul)(30, 40);
console.log("Multiplicación: " + multiplicar);
var dividir = (0, operaciones_js_1.dvr)(40, 0);
console.log("División:" + dividir);
